BestMovies/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BestMovies.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsSubscribetToNewsLetter { get; set; }
        public DateTime? BirthDate { get; set; }

        public int MembershipTypeId { get; set; }
        public MembershipType Membership { get; set; }
    }
}

BestMovies/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BestMovies.Models
{
    public class Genre
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

BestMovies/Models/MembershipType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BestMovies.Models
{
    public class MembershipType
    {
        public int Id { get; set; }

        public string Duration { get; set; }

        public decimal SignUpFree { get; set; }

        public int DiscountRate { get; set; }
    }
}

BestMovies/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BestMovies.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        
        public int? GenreId { get; set; }
        public Genre Genre { get; set; }

        [Required] public DateTime ReleaseTime { get; set; }
        [Required] public DateTime DateAdded { get; set; }
        [Required] public int NumbetInStok { get; set; }
    }
}

BestMovies/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using BestMovies.Models;
using BestMovies.Persistance.Repositories;

namespace BestMovies.Controllers
{
    public class CustomerController : Controller
    {


        // GET: Customer
        public ActionResult Index()
        {
            List<Customer> customers = null;

         
                customers = new DB_Context().Customers.Include("Membership").ToList();
            
            //catch (Exception e)
            //{
            //    return Content("We dont have any customer Yet");
            //}

            return View(customers);
        }

        public ActionResult Details(int? id)
        {
           
            var customers = new DB_Context().Customers;

            Customer customer = null;
            try
            {
                customer = customers.Include("Membership").First(c => c.Id == id);
            }
            catch (Exception e)
            {
                return Content("We dont have this customer");
            }

            return View(customer);
        }
    }
}

BestMovies/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BestMovies.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BestMovies/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BestMovies.Models;
using BestMovies.Persistance.Repositories;

namespace BestMovies.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Index()
        {
            var DB = new DB_Context();

            return View(DB.Movies.ToList());
        }

        public ActionResult Details(int? id)
        {

            var DB = new DB_Context();

            Movie movie = null;
            try
            {
                movie = DB.Movies.Include("Genre").First(c => c.Id == id);
            }
            catch (Exception e)
            {
                return Content("We dont have this movie");
            }

            return View(movie);
        }
    }
}

BestMovies/Views/Customer/Details.cshtml
@model BestMovies.Models.Customer

@{
    ViewBag.Title = "Details";
}

<h2>@Model.FirstName @Model.LastName</h2>
<br/>
<span>@Model.Membership.Duration</span>
<br/>
<span>@Model.BirthDate.Value.ToShortDateString()</span>

BestMovies/Views/Customer/Index.cshtml
@model List<BestMovies.Models.Customer>

@{
    ViewBag.Title = "Customers";
}

<h2>Customers</h2>

<div class="container">
    @foreach (var customer in Model)
    {
        <a href="@Url.Action("Details","Customer",new {Id = customer.Id})">@customer.FirstName @customer.LastName</a> <span>, Membership Type : @customer.Membership.Duration</span><br />
@*        @Html.ActionLink(customer.FirstName+customer.LastName, "Details", "Customers" , 0) @customer.FirstName @customer.LastName*@
    }
</div>

BestMovies/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BestMovies/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BestMovies/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

BestMovies/Views/Movie/Details.cshtml
@model BestMovies.Models.Movie

@{
    ViewBag.Title = "Details";
}

<h2>@Model.Name by @Model.Author</h2>

<ul>
    <li> Genre : @Model.Genre.Name</li>
    <li> Release Date : @Model.ReleaseTime.ToShortDateString() </li>
    <li> Date Added : @Model.DateAdded.ToShortDateString() </li>
    <li> Number in Stock : @Model.NumbetInStok </li>
</ul>

BestMovies/Views/Movie/Index.cshtml
@model List<BestMovies.Models.Movie>

@{
    ViewBag.Title = "Index";
}

<h2>Movies</h2>


<div class="container">
    @foreach (var movie in Model)
    {
        <a href="@Url.Action("Details", "Movie" , new {Id = movie.Id})">@movie.Name:</a>
        <br/>
        <p>by @movie.Author </p>
        <br/>
        @*        @Html.ActionLink(customer.FirstName+customer.LastName, "Details", "Customers" , 0) @customer.FirstName @customer.LastName*@
    }
</div>

BestMovies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                    <li>@Html.ActionLink("Movies", "Index", "Movie")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>